version: '3.0'

services:
  bludit:
    build: ./
    container_name: bludit
    volumes:
      - html:/var/www           # Bludit home
      - nginx:/etc/nginx        # Nginx config
    ports:
      - 8004:80
    restart: always
    cpu_shares: 50
    mem_limit: 64m
    memswap_limit: 64m

volumes:
  html: {}
  nginx: {}

networks:
  default:
